### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [jmichlitsch/mod_0_skills#1]
@jmichlitsch overall, pretty solid work on this. It's not quite passing, but you've earned the opportunity to be able to make some updates that can promote you to `technical ready`! Please update the following:

* [ ] Since you are in back-end, make sure that that all of your attributes and methods are `snake_case`.
* [ ] For a food class, food should not be in the name of either attributes or methods as it is redundant. Please update all of your attrs and methods per this reccomendation.
  * ie. `is_the_food_solid` should just be `is_solid`
* [ ] make sure that all of your methods update or utilize your data model in some meaningful way (you're doing this for the most part, but your `is_the_food_solid` method is simply reading an attribute, therefore not meeting this rule

**Comment by jmichlitsch** [comment]
@damwhit I believe I have made all the changes you have asked for but if I missed anything, just let me know.

**Comment by damwhit** [comment]
@jmichlitsch this is close. Please go back and make sure that all of your data is a valid data type and change all that are not within your example object files

**Comment by jmichlitsch** [comment]
@damwhit I fixed my string data types to make them valid. Been forgetting to put them in quotations as of late.
